apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: MYSQLDB_HOST
              value: {{ include "myapp.fullname" . }}-mysql.{{ .Values.namespace }}.svc.cluster.local
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-user
            - name: MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-password
            - name: MYSQLDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-database
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 10 }}
      {{- end }}

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: 1  # Adjust as per your MySQL deployment needs
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.mysqlRootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.mysqlDatabase }}"
            - name: MYSQL_USER
              value: "{{ .Values.mysql.mysqlUser }}"
            - name: MYSQL_PASSWORD
              value: "{{ .Values.mysql.mysqlPassword }}"
          ports:
            - containerPort: {{ .Values.mysql.mysqlPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

