apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: MYSQLDB_HOST
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-host
            - name: MYSQLDB_USER
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-user
            - name: MYSQLDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-password
            - name: MYSQLDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: myapp-secret
                  key: mysqldb-database
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}

