apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-mysql
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql

