namespace: microapp

replicaCount: 2

image:
  repository: luisjuanguerrero026/myapp
  tag: "1.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: myapp.local
      paths: ["/"]
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false

autoscaling:
  enabled: false

mysql:
  enabled: true
  image: mysql:5.7
  mysqlRootPassword: rootpassword
  mysqlUser: myuser
  mysqlPassword: secretpassword
  mysqlDatabase: mydatabase
  mysqlPort: 3306
  service:
    type: ClusterIP
    port: 3306

